### ISSUE TITLE
Add presto config / CLI flags to use this plugin

### ISSUE THREAD

**Issue by Gustav-Simonsson** [xiaoyao1991/presto-ethereum#9]
From presto documentation alone it's difficult to see how to access the plugin through the CLI. For example, after simply starting the CLI the Ethereum tables are not available.

**Comment by xiaoyao1991** [comment]
If you have loaded the plugin in presto installation, then you could start the CLI in this way:  
`presto-cli --server <your presto server endpoint, normally it's something like localhost:8080> --catalog ethereum --schema default`
and then Ethereum tables will be there. 

My README is not yet in a good shape. I will restructure and put more details such as how to load plugin, etc.

**Comment by kirillseva** [comment]
How does one load plugin in presto installation? Please expand #4 in your installation readme for those of us that see java for the first time

**Comment by xiaoyao1991** [comment]
@Gustav-Simonsson @kirillseva I've updated the readme with more details on installation and loading presto plugins. Let me know if it needs more details

**Comment by Gustav-Simonsson** [comment]
@xiaoyao1991 thanks! got it working now :+1:
